apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-sep4-4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-sep4-4:3350e3d34c7ed6a5a309fed5467d092728f16606@sha256:9fbda1d35bae3ece6aadd86e9de02f2dd3021dbdb571c172f4acef99f810d160 # use pre-built to bootstrap 
          name: app-inference
